<a href="https://colab.research.google.com/github/manas1313/Tensorflow/blob/main/00_tensorflow_fundameltals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##We are going to cover some of the most fundamental concepts of tensorflow
we are goin to cover:
* Introduction to tensors
* getting info from tensors
* manipulating tensors
* Tensors & NumPy
* Using @tf.functions(a way to speed up your regular Python functions)
* Using GPUs with Tensorflow(orTPUs)
* Excersise to try yourself

In [2]:
#Introductions to Tebsors

In [3]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [6]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
# Check the number of dimensions of a tensor (ndim stands for of dimensions)
scalar.ndim

0

In [8]:
# Cerate a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [9]:
# check the dimension of vector
vector.ndim

1

In [11]:
# Cerate a matrix (has more than one element)
matrix =  tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [12]:
matrix.ndim

2

In [14]:
#Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype = tf.float16) # specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [15]:
# What's the number of dimension of another matrix?
another_matrix.ndim

2

In [32]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [33]:
tensor.ndim

3

### Cerating tensor with `tf.Variable


In [21]:
# Create the same tensor with tf.Variable() as above

changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor, unchangable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [22]:
# Let's try change one of the emements in our changable tensor
changable_tensor[0] = 7
changable_tensor

TypeError: ignored

In [23]:
# how about we try .assign()
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [25]:
# Let's try change our unchangable tensor
unchangable_tensor[0].assign(7)


AttributeError: ignored

### Cerate random tensors
Random tensors are tensors of some abitrary size with contain random numbers

In [27]:
# Create two random (but the same) tensors

In [34]:
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape =(3,2))
random_1
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))

# Are they equal?
random_1, random_2, random_1 ==  random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# Suffle the order of the elements

In [41]:
# Suffle a tensor (valuable for when you want suffle your data so the inherent order doesnot effect learning )
not_suffeled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_suffeled.ndim
# shuffle our non-suffled tensor
tf.random.shuffle(not_suffeled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [39]:
not_suffeled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [49]:
# shuffle our non-suffled tensor
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_suffeled, seed=42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

** Exercise: ** read through Tensorflow documentation on ramdom seed generation:
https://www.tensorflow.org/api_docs/python/tf/random/set_seed  and practice writing 5 random tensors and suffle them.

### Other ways to make tensors


In [51]:
# Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [54]:
# Create a tensor of all zeros
tf.zeros(shape =(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Turn NumPy arrays into tensors
The main differnes between NumPy arrays and Tensors is that tensors can run on GPu mush faster


In [56]:
# you can also turn NumPy arrays into tensors
import numpy as np

numpy_A = np.arange(1,25, dtype= np.int32) # create a NumPy array between 1 and 25
numpy_A =


# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [62]:
A = tf.constant(numpy_A, shape= (2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [63]:
A.ndim

3